spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: XYZ
            clientSecret: XYZ
          google:
            clientId: XYZ
            clientSecret: XYZ
          azure:
            clientName: azure
            clientId: XYZ
            clientSecret: XYZ
            scope: openid, email
            provider: azure
        provider:
          azure:
            issuerUri: XYX